version: "3.8"

services:
  mysql-db:
    container_name: db_expenses
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: db_expenses
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: pas123
      MYSQL_PASSWORD: pas123

    ports:
      - "3307:3306"